### ISSUE TITLE
Re-arrange HTML template to match desired use

### ISSUE THREAD

**Issue by KentHinaloc** [MMS-142-Group-E/mms142-groupe-2022.github.io#2]
Note: Parenthesis specifies the HTML template section to be used accordingly for the said content.

Proposed Order: 
1. What is it or how does it work (Welcome...)
2. Members (Members...)
3. Brief History and Current Situation (Brief History) 
4. Extended Definition of Disruptive Technology (Testimonies)
5. What Field or Market is it Disrupting (Market)
6. Why is it Disruptive (How to Sell Digital Product)
7. Conclusion (_pending_)

**Comment by flgapasin24** [comment]
Hello, Soji and I made the conclusion part na. still needs some editing pero  do we work on that na? Ilalagay lang ba namin sa conslusion part, then kami na bahala mag format ? thank you.
